# -*- coding: utf-8 -*-
# Generated by Django 2.2 on 2019-04-12 09:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256)),
                ('ssl_expire', models.DateTimeField(verbose_name='expire date')),
            ],
        ),
    ]
