# -*- coding: utf-8 -*-
# Generated by Django 2.2 on 2019-04-12 09:43
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_ssl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites',
            new_name='Site',
        ),
    ]
