# Generated by Django 2.2 on 2019-04-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ssl', '0003_auto_20190412_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='ssl_expire',
            field=models.DateTimeField(blank=True, verbose_name='expire date'),
        ),
    ]
