# Generated by Django 2.2 on 2019-04-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ssl', '0007_auto_20190412_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='ssl_expire',
            new_name='expires',
        ),
        migrations.AddField(
            model_name='site',
            name='error',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
