# -*- coding: utf-8 -*-
# Generated by Django 2.2 on 2019-04-12 10:10
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_ssl', '0008_auto_20190412_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='domain',
            new_name='hostname',
        ),
    ]
