# Generated by Django 2.2 on 2019-04-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ssl', '0009_auto_20190412_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='hostname',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
