version: '3.8'
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./docker/files/etc/my.cnf:/etc/my.cnf
    env_file:
      - src/backend/.env

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./data/redis:/data

  app-dev:
    image: app:dev
    build:
      context: .
      target: development
    restart: always
    env_file:
      - src/backend/.env
    volumes:
      - ./src/backend:/app
      - ./data/static:/app/static
      - ./data/log:/var/log/swissmooc-extras
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  app:
    image: swissmooc-extras-app:production
    build:
      context: .
      target: production
    restart: always
    env_file:
      src/backend/.env-production
    volumes:
      - ./src/backend:/app
    depends_on:
      - db
      - redis

  nginx:
    image: swissmooc-extras-nginx:production
    build:
      context: .
      target: nginx
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - ./docker/files/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app

  dockerize:
    image: jwilder/dockerize
