# -*- coding: utf-8 -*-
# Generated by Django 2.2 on 2019-04-23 14:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0005_organisation_publickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='recipient',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
