# -*- coding: utf-8 -*-
# Generated by Django 2.2 on 2019-05-09 12:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0015_auto_20190509_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedumptable',
            name='db_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
