# -*- coding: utf-8 -*-
# Generated by Django 4.1.10 on 2023-08-28 08:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0024_course_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='structure',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
