# -*- coding: utf-8 -*-
# Generated by Django 4.1.10 on 2023-08-28 11:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0025_alter_course_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
