# -*- coding: utf-8 -*-
# Generated by Django 4.1.10 on 2023-08-28 12:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0026_alter_organisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
