# -*- coding: utf-8 -*-
# Generated by Django 4.1.10 on 2023-08-28 13:49
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0028_alter_coursedump_is_encypted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_id',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_id', 'organisation')},
        ),
    ]
