# -*- coding: utf-8 -*-
# Generated by Django 4.1.12 on 2023-11-01 14:37
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0029_rename_name_course_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='public_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='split_logs.publickey'),
        ),
    ]
