# Generated by Django 2.2 on 2019-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.CharField(choices=[('0', 'not active'), ('1', 'active')], default='0', max_length=1),
        ),
    ]
