# -*- coding: utf-8 -*-
# Generated by Django 2.2 on 2019-05-01 11:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0008_course_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
