# Generated by Django 2.2 on 2019-05-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0009_auto_20190501_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'organisation')},
        ),
    ]
