# -*- coding: utf-8 -*-
# Generated by Django 2.2 on 2019-05-09 09:39
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0013_coursedumptables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDumpTables',
            new_name='CourseDumpTable',
        ),
        migrations.AddField(
            model_name='coursedump',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='split_logs.CourseDumpTable'),
            preserve_default=False,
        ),
    ]
