# Generated by Django 2.2 on 2019-05-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0014_auto_20190509_0939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursedump',
            unique_together={('course', 'table', 'date')},
        ),
    ]
