# Generated by Django 2.2 on 2019-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0016_coursedumptable_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedumptable',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'mysql'), ('mongo', 'mongo')], default='mysql', max_length=128),
        ),
    ]
