# Generated by Django 3.2.12 on 2022-06-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_logs', '0022_fileoriginaldocker'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
